### ISSUE TITLE
Request to start tagging releases

### ISSUE THREAD

**Issue by dagostinelli** [siffiejoe/lua-moon#1]
I enjoy using your library.  I was just wondering if you could start tagging some releases?  I've been using the library on a little project for a year or so, I had a question and went back to GitHub to review the code so I can answer my question.  But now I just noticed that the API has changed and there is not a tag for me to go back and reference the previous API.  For instance, moon_checkudata and moon_testudata are gone now.  I'm not entirely sure which commit represents the version that I'm using in my project so that I can go back and reference it.  I'm going to figure that out by bisecting, so it's going to be OK.  I just thought I'd toss in a friendly request to start tagging some releases.

Maybe this is just a reflection of the library not yet having any formal releases yet?  

In any event, it's a nice library.  Good job on it.

**Comment by siffiejoe** [comment]
I've tagged the commit immediately before the major rewrite as v1.0.0. This version is probably compatible with what you are using. I've removed most compatibility functions (like `moon_checkudata`) during the rewrite, because I now use [`Compat-5.3`](https://github.com/keplerproject/lua-compat-5.3) for this, which is much more comprehensible. Main point of the rewrite was to improve the functions dealing with userdata objects. Quote from the commit log:

> The functions for defining/creating objects have been enhanced to
> allow type-safe access to members of tagged unions, to transparently
> use the same metatables for boxed/unboxed objects, to support
> different object lifetimes, to support multiple different ways of
> constructing/destructing objects, and to support releasing resources
> before the object is destroyed by the GC.

**Comment by dagostinelli** [comment]
Perfect. Thanks!
