### ISSUE TITLE
Is there a lua-moon idiom for extending an object from Lua?

### ISSUE THREAD

**Issue by dagostinelli** [siffiejoe/lua-moon#3]
Related to #2, is there a way to extend the object without implementing __newindex in C?

```
struct MyObject *instance;
instance = calloc(1, sizeof(struct MyObject));
*moon_newpointer(L, "MyObject", free) = instance;
```

And then in Lua

```
local instance = getInstanceCreatedOnCSide()
instance.x = 10

```

Currently it errors out saying `attempt to index a userdata value`.  

I could implement a __newindex function in C to handle this (it's what I am currently doing)  

I was wondering if there was an idiomatic way to do this.

**Comment by siffiejoe** [comment]
No, `__newindex` is the way to go. I'd suggest storing the extra data in a uservalue table for easy and fast access in the `__newindex` metamethod. If you don't use `moon_newfield()` (which is a variant of `moon_newpointer()` for  objects embedded in other objects), you have the uservalue table all for yourself.
E.g.:

``` C
static int new_index(lua_State* L) {
  struct MyObject* o = moon_checkobject(L, 1, "MyObject");
  char const* key = lua_tostring(L, 2);
  if (key && strcmp(key, "y") == 0) {
    /* handle fields of MyObject structure this way */
    int i = moon_checkint(L, 3, 0, INT_MAX);
    o->y = i;
  } else {
    /* store unknown keys in the uservalue table */
    lua_getuservalue(L, 1); /* push uservalue table */
    lua_pushvalue(L, 2); /* push key */
    lua_pushvalue(L, 3); /* push value */
    lua_settable(L, -3); /* store in uservalue table */
  }
  return 0;
}
```

You'll also have to modify your `__index` to retrieve unknown keys from the uservalue table, and make sure that the uservalue table actually exists on your userdata ...

**Comment by dagostinelli** [comment]
It looks like sometimes the uservalue table isn't present at the time new_index is called, so I made sure it's there by creating a table and setting it as the uservalue if it's not present.  Will that mess with anything in lua-moon?

```
/* makes sure that the userdata table is now on the stack*/
/* idx is the index to the userdata object involved*/
void mystuff_pushuservalue(lua_State *L, int idx)
{
    luaL_checktype(L, idx, LUA_TUSERDATA);
    lua_getuservalue(L, idx); /* push uservalue table */
    if (lua_isnil(L, -1)) /* does not have a uservalue table yet */
    {
        lua_newtable(L); /* create a table */
        lua_setuservalue(L, idx); /* associate the new table with the userdata */
        lua_pop(L, 1);
        lua_getuservalue(L, idx); /* push uservalue table */
        assert(lua_type(L, -1) == LUA_TTABLE);
    }
}
```

I changed new_index a little different from your example (only because the table isn't always there).  How does this look?

```
static int __newindex( lua_State* L )
{
    struct MyObject* o = moon_checkobject(L, 1, "MyObject");
    const char* key = luaL_checkstring(L, 2);

    if (key && strcmp(key, "y") == 0){
        /* handle fields of MyObject structure this way */
        int i = moon_checkint(L, 3, 0, INT_MAX);
        o->y = i;
        return 0;
    } else {
        /* store unknown keys in the uservalue table */
        mystuff_pushuservalue(L, 1);
        lua_pushvalue(L, 3);
        lua_setfield(L, -2, key);
        return 1;
    }
}
```

Then in __index, it's similar

```
static int __index(lua_State* L)
{
    struct MyObject* o = moon_checkobject(L, 1, "MyObject");
    const char* s = luaL_checkstring(L, 2);
    if(0 == strcmp(s, "firstName"))
    {
        lua_pushstring(L, o->firstName);
    }
    else
    {
        /* look up unknown keys in the uservalue table */
        mystuff_pushuservalue(L, 1);
        lua_getfield(L, -1, s);
    }
    return 1;
}
```

One problem I'm having is that the table is not preserved.  I'm calling `moon_newpointer()` every time I push the object on to the stack from C.  This is generating a new userdata object right?  Any advice on re-using the same lua-moon wrapper and not call `moon_newpointer()` every time?

**Comment by siffiejoe** [comment]
Userdatas don't have uservalue tables by default. You have to explicitly set them using `lua_setuservalue()`. I'd recommend doing so directly after you've allocated the userdata, but in Lua 5.2+ you can do so later and on demand as well. `moon_newfield()` is the only function that sets/modifies the uservalue table for its own purposes. The other functions don't touch it (well `moon_getuvfield()` and `moon_setuvfield()` do, but only on your behalf).

Regarding your `__newindex()` function: It looks ok, but it only works for string keys (in fact it will crash for keys that are not convertible to strings). My version works for arbitrary keys (except `nil`).

A possible solution for your last problem consist of two parts: The first part is a table that has lightuserdata keys and full userdata values. Whenever you want to get your C object into the Lua VM, you push it as a lightuserdata and look up the corresponding full userdata in the table (you only allocate a new userdata if it's not in the table already). Usually this table is weak so that the GC can still collect the userdatas when they become unreachable. There is a function for that in this toolkit: `moon_getcache()`. If you want to keep the userdata alive even if it is unused in Lua, you can use `luaL_ref()` for that. But beware that in this case the userdata won't be collected until you close the Lua state or call `luaL_unref()` with the matching id.
