### ISSUE TITLE
Add a __gc or destructor to be called when the gc fires

### ISSUE THREAD

**Issue by dagostinelli** [siffiejoe/lua-moon#4]
I have been doing memory cleanup manually (calloc/free).  Now I'd like to give __gc a shot.  I'm a little confused on how to set this up.  When do it as follows, the __gc method is never called.  In moon.c, I can see that there is a default __gc being added, but no way to add my own except for when I use moon_newobject.  I am trying something like this...

```
int myobject_open(lua_State* L)
{
    luaL_Reg const _instance_methods[] = {
        { "__index", __index },
        { "__newindex", __newindex },
        { "__gc", __gc},
        { NULL, NULL }
    };
    luaL_Reg const _static_methods[] = {
        { "new", __new },
        { NULL, NULL }
    };
    moon_defobject(L, MYTYPENAME, sizeof(my_type), _instance_methods, 0);
    lua_newtable(L);
    luaL_setfuncs(L, _static_methods, 0);
    return 1;
}
```

Later, the __gc method is not being called.  

I haven't been using moon_newobject() and maybe that's the problem.  Instead, at certain points in my program, I am `calloc`ing structs and then passing them as lua objects.  I would prefer to continue that.

**Comment by siffiejoe** [comment]
Yes, the default `__gc` metamethod generated by `moon_defobject()` uses the function pointer passed to `moon_newobject()` or `moon_newpointer()`. The point is that the destructor might depend on the specific circumstances when the userdata was created. E.g. in the Lua standard library there is `io.open()` and `io.popen()`, which both return Lua file handle userdatas, but one requires the use of `fclose()` and the other `pclose()`. Similarly, you can bind a global object using `moon_newpointer()`:

``` lua
void** ptr = moon_newpointer( L, "mystruct", 0 ); /* no cleanup function */
*ptr = &global_object;
```

or a malloc'ed object:

``` lua
void** ptr = moon_newpointer( L, "mystruct", free );
*ptr = calloc( 1, sizeof( mystruct ) );
```

The `__gc` also needs to differentiate between direct and indirect objects (in the first case all memory is allocated by the `lua_newuserdata()` call, in the second the userdata only holds a pointer to the real object), and support early destruction using `moon_killobject()`.

That's why all moon objects have a common `__gc` metamethod and the real cleanup function is passed in via the `moon_new{object,pointer}()` call.
